-- ============================================================
-- DOGEE COFFEE CRM — Database Schema (PRD V3)
-- Jalankan SQL ini di Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. DEFINISI ENUM
CREATE TYPE coffee_role AS ENUM ('ADMIN', 'MEMBER', 'GUEST');
CREATE TYPE loyalty_tier AS ENUM ('SILVER', 'GOLD', 'PLATINUM');
CREATE TYPE order_status AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED');

-- 2. TABEL PROFILES (ekstensi auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    role coffee_role DEFAULT 'MEMBER'::coffee_role NOT NULL,
    tier loyalty_tier DEFAULT 'SILVER'::loyalty_tier NOT NULL,
    total_points INT DEFAULT 0 NOT NULL,
    phone_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. TABEL PRODUCTS
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    price_base NUMERIC NOT NULL,
    stock_qty INT NOT NULL DEFAULT 100,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 4. TABEL BOOKINGS
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity INT DEFAULT 1 NOT NULL,
    total_final_price NUMERIC NOT NULL,
    points_credited INT DEFAULT 0 NOT NULL,
    status order_status DEFAULT 'PENDING_PAYMENT'::order_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 5. TABEL CONTACTS
CREATE TABLE public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    is_resolved BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 6. TABEL NEWSLETTERS
CREATE TABLE public.newsletters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- AUTO-CREATE PROFILE ON SIGNUP (TRIGGER)
-- ============================================================

-- Function: auto-create profile when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, role, tier)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
        'MEMBER'::coffee_role,
        'SILVER'::loyalty_tier
    );
    RETURN NEW;
END;
$$;

-- Trigger: run after a new auth user is confirmed
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletters ENABLE ROW LEVEL SECURITY;

-- PROFILES
CREATE POLICY "Public profiles are readable by everyone"
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- PRODUCTS
CREATE POLICY "Products are viewable by everyone"
    ON public.products FOR SELECT USING (true);

CREATE POLICY "Only admins can modify products"
    ON public.products FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'
        )
    );

-- BOOKINGS
CREATE POLICY "Members can view own bookings"
    ON public.bookings FOR SELECT
    USING (auth.uid() = member_id);

CREATE POLICY "Members can insert own bookings"
    ON public.bookings FOR INSERT
    WITH CHECK (auth.uid() = member_id);

CREATE POLICY "Admins have full booking access"
    ON public.bookings FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'
        )
    );

-- CONTACTS (anonymous insert allowed)
CREATE POLICY "Anyone can submit contact form"
    ON public.contacts FOR INSERT WITH CHECK (true);

CREATE POLICY "Only admins can read contacts"
    ON public.contacts FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'
        )
    );

-- NEWSLETTERS (anonymous insert allowed)
CREATE POLICY "Anyone can subscribe newsletter"
    ON public.newsletters FOR INSERT WITH CHECK (true);

CREATE POLICY "Only admins can read newsletters"
    ON public.newsletters FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN'
        )
    );

-- ============================================================
-- SEED DATA — Menu Products Dummy
-- ============================================================

INSERT INTO public.products (name, category, description, price_base, stock_qty, image_url) VALUES
('Caramel Signature Latte', 'Signature', 'Perpaduan espresso dengan karamel premium dan steamed milk', 38000, 100, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=300&q=80'),
('Hazelnut Affogato', 'Signature', 'Affogato klasik dengan sirup hazelnut panggang', 42000, 100, 'https://images.unsplash.com/photo-1578645635737-6a88f706a5e3?w=300&q=80'),
('Gula Aren Cream Latte', 'Signature', 'Latte dengan gula aren asli dan cream foam', 35000, 100, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=300&q=80'),
('Cappuccino', 'Classic', 'Espresso klasik dengan foam susu tebal', 28000, 100, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=300&q=80'),
('Caffe Latte', 'Classic', 'Espresso smooth dengan steamed milk', 25000, 100, 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=300&q=80'),
('Espresso Doppio', 'Classic', 'Double shot espresso pekat', 22000, 100, 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=300&q=80'),
('Mocha', 'Classic', 'Perpaduan espresso, cokelat, dan steamed milk', 30000, 100, 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=300&q=80'),
('Matcha Latte', 'Non-Coffee', 'Matcha premium Jepang dengan steamed milk', 32000, 100, 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=300&q=80'),
('Chocolate Frappe', 'Non-Coffee', 'Minuman cokelat dingin dengan whipped cream', 35000, 100, 'https://images.unsplash.com/photo-1527794828616-f3724cf13943?w=300&q=80'),
('Blue Sakura Tea', 'Non-Coffee', 'Teh bunga sakura biru alami dengan honey', 30000, 100, 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=300&q=80');

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
-- SELECT * FROM public.profiles;
-- SELECT * FROM public.products;
-- SELECT * FROM public.contacts;
-- SELECT * FROM public.newsletters;
